#===============================================================================
# Trainer Generator
#===============================================================================
# TRAINERS - Trainer types included
# GUARANTEED - A Pokemon guaranteed to have
# WHITELIST - All the Pokemon that can be used
# ONLYTYPE - The only type the trainer uses
# EGGGROUP - Filter by egg groups
# LEARNMOVE - Uses only Pokemon that can learn this move by level up
# MAINPOKEMON - Pokemon added to the list after all filters (Can be used to add new species or to increase the chances for a specie)
# POWER -Base total stats the Pokemon should have
# SPECIAL (VARIED) - Use different types over the party
# SPECIAL (COMBINATION) - Use a combination of types over the party
# SPECIAL (COLLECTOR) - All Pokemon in the party are the same specie
#===============================================================================
module TrainerClasses_Types
    ACETRAINER = {
        :TRAINERS => [:ACEDUO,:ACETRAINER_F,:ACETRAINER_F2,:ACETRAINER_3,:ACETRAINER_M,:ACETRAINER_M2,:ACETRAINER_M3,:COOLCOUPLE,:COOLTRAINER_M,:COOLTRAINER_F],
        :POWER => [450],
        :SPECIAL => [:VARIED]
    }
    AROMALADY = {
        :TRAINERS => [:AROMALADY,:AROMALADY2],
        :ONLYTYPE => [:GRASS],
        :MAINPOKEMON => [:ROSELIA,:SHROOMISH,:ODDISH,:PETILIL,:BOUNSWEET,:FOMANTIS,:SMOLIV]
    }
    ARTIST = {
        :TRAINERS => [:ARTIST_F,:ARTIST_M],
        :LEARNMOVE => [:COPYCAT,:MIMIC],
        :MAINPOKEMON => [:MRMIME,:BONSLY,:KRICKETOT,:SMEARGLE,:GRAFAIAI]
    }
    BACKPACKER = {
        :TRAINERS => [:BACKPACKER],
        :ONLYTYPE => [:NORMAL,:ROCK,:GROUND,:FLYING]
    }
    BATTLEGIRL = {
        :TRAINERS => [:BATTLEGIRL,:BATTLEGIRL2,:BATTLEGIRL3],
        :ONLYTYPE => [:FIGHTING],
        :MAINPOKEMON => [:MEDITITE,:MAKUHITA,:SHROOMISH,:MACHOP,:MIENFOO,:PANCHAM,:CLOBBOPUS,:PAWMI]
    }
    BEAUTY = {
        :TRAINERS => [:BEAUTY,:BEAUTY2,:BEAUTY3,:BEAUTY4],
        :WHITELIST => [:MARILL,:GOLDEEN,:WAILMER,:KECLEON,:SEVIPER,:LOTAD,:SHROOMISH,:NUMEL,:CARVANHA,:SPHEAL,:SPOINK,:POOCHYENA,:CLAMPERL,:CORPHISH,:HORSEA,:LUVDISC,
        :ODDISH,:BELLSPROUT,:NIDORANfE,:CLEFAIRY,:MEOWTH,:GLAMEOW,:BURMY,:FINNEON,:PSYDUCK,:ROSELIA,:BUNEARY,:SKITTY,:SENTRET,
        :MINCCINO,:DEERLING,:FLABEBE,:SKIDDO,:SPRITZEE,:SWIRLIX,:CUTIEFLY,:BOUNSWEET,:COMFEY,:MILCERY,:HATENNA,:FIDOUGH,:TANDEMAUS]
    }
    BIKER = {
        :TRAINERS => [:BIKER,:BIKER2],
        :ONLYTYPE => [:POISON,:FIRE],
        :MAINPOKEMON => [:KOFFING,:GRIMER,:EKANS,:GULPIN,:TRUBBISH,:STUNKY,:VAROOM]
    }
    BIRDKEEPER = {
        :TRAINERS => [:BIRDKEEPER,:BIRDKEEPER2,:BIRDKEEPER3,:BIRDKEEPER4],
        :ONLYTYPE => [:FLYING],
        :MAINPOKEMON => [:PIDGEY,:SPEAROW,:TAILLOW,:STARLY,:PIDOVE,:FLETCHLING,:PIKIPEK,:ROOKIDEE,:WATTREL]
    }
    BLACKBELT = {
        :TRAINERS => [:BLACKBELT,:BLACKBELT2,:BLACKBELT3],
        :ONLYTYPE => [:FIGHTING],
        :MAINPOKEMON => [:MACHOP,:MAKUHITA,:MEDITITE,:MANKEY,:TYROGUE,:RIOLU,:TIMBURR,:MIENFOO,:PANCHAM,:HAWLUCHA,:CRABRAWLER,:CLOBBOPUS]
    }
    BREEDER = {
        :TRAINERS => [:BREEDER_F,:BREEDER_F2,:BREEDER_F3,:BREEDER_F4,:BREEDER_M,:BREEDER_M2],
        :SPECIAL => [:VARIED]
    }
    BUGCATCHER = {
        :TRAINERS => [:BUGCATCHER,:BUGCATCHER2,:BUGCATCHER3,:BUGMANIAC],
        :ONLYTYPE => [:BUG],
        :MAINPOKEMON => [:CATERPIE,:WEEDLE,:WURMPLE,:KRICKETOT,:SEWADDLE,:SCATTERBUG,:GRUBBIN,:BLIPBUG,:TAROUNTULA]
    }
    BURGLAR = {
        :TRAINERS => [:BURGLAR,:BURGLAR2],
        :ONLYTYPE => [:FIRE],
        :MAINPOKEMON => [:KOFFING,:GRIMER,:GROWLITHE,:VULPIX,:NUMEL,:HOUNDOUR,:ZORUA,:LITLEO,:SALANDIT,:SCORBUNNY]
    }
    BUTLER = {
        :TRAINERS => [:BUTLER],
        :ONLYTYPE => [:FLYING]
    }
    CAMERAMAN = {
        :TRAINERS => [:CAMERAMAN],
        :ONLYTYPE => [:ELECTRIC]
    }
    CAMPER = {
        :TRAINERS => [:CAMPER_F,:CAMPER_M,:CAMPER_M2,:CAMPER_M3],
        :SPECIAL => [:VARIED]
    }
    CHANELLER = {
        :TRAINERS => [:CHANELLER],
        :ONLYTYPE => [:GHOST]
    }
    CHEF = {
        :TRAINERS => [:CHEF],
        :SPECIAL => [:COMBINATION,[:WATER,:FIRE,:GRASS]]
    }
    COLLECTOR = {
        :TRAINERS => [:COLLECTOR],
        :SPECIAL => [:COLLECTOR],
    }
    CRUSHTRAINER = {
        :TRAINERS => [:CRUSHGIRL,:CRUSHKIN,:CRUSHKIN2],
        :ONLYTYPE => [:FIGHTING]
    }
    CUEBALL = {
        :TRAINERS => [:CUEBALL],
        :ONLYTYPE => [:FIGHTING,:DARK]
    }
    CUTECOUPLE = {
        :TRAINERS => [:CUTECOUPLE],
        :GUARANTEED => [:SMEARGLE]
    }
    DELINQUENT = {
        :TRAINERS => [:DELINQUENT],
        :ONLYTYPE => [:DARK]
    }
    DIVER = {
        :TRAINERS => [:DIVER_F,:DIVER_M],
        :ONLYTYPE => [:WATER]
    }
    DRAGONTAMER = {
        :TRAINERS => [:DRAGONTAMER],
        :ONLYTYPE => [:DRAGON],
        :MAINPOKEMON => [:DRATINI,:BAGON,:GIBLE,:DEINO,:GOOMY,:JANGMOO,:DREEPY,:FRIGIBAX]
    }
    ENGINEER = {
        :TRAINERS => [:ENGINEER],
        :ONLYTYPE => [:ELECTRIC],
        :MAINPOKEMON => [:MAGNEMITE,:VOLTORB,:ELEKID,:ELECTRIKE,:SHINX,:JOLTIK,:TYNAMO,:HELIOPTILE,:CHARJABUG,:TOXEL,:TADBULB,:WATTREL]
    }
    EXPERT = {
        :TRAINERS => [:EXPERT_F,:EXPERT_M],
        :ONLYTYPE => [:FIGHTING],
        :MAINPOKEMON => [:MACHOP,:MAKUHITA,:MEDITITE,:RIOLU,:TIMBURR,:MIENFOO,:PANCHAM,:CRABRAWLER,:CLOBBOPUS]
    }
    FAIRYTALEGIRL = {
        :TRAINERS => [:FAIRYTALEGIRL],
        :ONLYTYPE => [:PSYCHIC,:NORMAL]
    }
    FISHERMAN = {
        :TRAINERS => [:FISHERMAN,:FISHERMAN2,:FISHERMAN3,:FISHERMAN4],
        :ONLYTYPE => [:WATER],
        :MAINPOKEMON => [:MAGIKARP,:GOLDEEN,:FEEBAS,:FINNEON,:BASCULIN,:WISHIWASHI,:ARROKUDA]
    }
    FURISODEGIRL = {
        :TRAINERS => [:FURISODEGIRL,:FURISODEGIRL2,:FURISODEGIRL3,:FURISODEGIRL4],
        :WHITELIST => [:EEVEE]
    }
    GAMBLER = {
        :TRAINERS => [:GAMBLER],
        :LEARNMOVE => [:HORNDRILL]
    }
    GARDENER = {
        :TRAINERS => [:GARDENER],
        :ONLYTYPE => [:GRASS,:BUG]
    }
    GENTLEMAN = {
        :TRAINERS => [:GENTLEMAN,:GENTLEMAN2,:GENTLEMAN3,:GENTLEMAN4],
        :WHITELIST => [:ELECTRIKE,:ZIGZAGOON,:CHATOT,:ZANGOOSE,:NIDORANfE,:NIDORANmE,:PIKACHU,:EEVEE,:CUBONE,:PSYDUCK,:GROWLITHE,:PONYTA,
        :STARLY,:HOOTHOOT,:MEOWTH,:ELECTRIKE,:MAREEP,:LILLIPUP,:FURFROU,:SKIDDO,:YAMPER,:FIDOUGH],
    }
    GUITARIST = {
        :TRAINERS => [:GUITARIST],
        :ONLYTYPE => [:ELECTRIC],
        :MAINPOKEMON => [:PIKACHU,:MAGNEMITE,:VOLTORB,:ELECTRIKE,:SHINX,:BLITZLE,:EMOLGA,:HELIOPTILE,:TOXEL,:PAWMI]
    }
    HEXMANIAC = {
        :TRAINERS => [:HEXMANIAC],
        :ONLYTYPE => [:PSYCHIC,:GHOST],
        :MAINPOKEMON => [:GASTLY,:MISDREAVUS,:SHUPPET,:DUSKULL,:DRIFLOON,:YAMASK,:LITWICK,:PHANTUMP,:PUMPKABOO,:MIMIKYU,:SINISTEA,:DREEPY]
    }
    HIKER = {
        :TRAINERS => [:HIKER,:HIKER2,:HIKER3],
        :ONLYTYPE => [:FIGHTING,:ROCK,:GROUND],
        :MAINPOKEMON => [:GEODUDE,:MACHOP,:ONIX,:RHYHORN,:ARON,:ROGGENROLA,:DRILBUR,:ROLYCOLY,:NACLI]
    }
    INTERVIEWERS = {
        :TRAINERS => [:INTERVIEWERS]
    }
    JUGGLER = {
        :TRAINERS => [:JUGGLER],
        :ONLYTYPE => [:PSYCHIC],
        :GUARANTEED => [:VOLTORB]
    }
    KINDLER = {
        :TRAINERS => [:KINDLER],
        :ONLYTYPE => [:FIRE],
        :MAINPOKEMON => [:GROWLITHE,:VULPIX,:PONYTA,:MAGMAR,:HOUNDOUR,:TORKOAL,:NUMEL,:PANSEAR,:LITLEO,:SALANDIT,:TURTONATOR,:ROLYCOLY]
    }
    LADY = {
        :TRAINERS => [:LADY,:LADY2,:LADY3,:LADY4],
        :WEAKER => [420]
    }
    LASS = {
        :TRAINERS => [:LASS,:LASS2,:LASS3],
        :ONLYTYPE => [:NORMAL,:GRASS],
        :MAINPOKEMON => [:PIDGEY,:RATTATA,:JIGGLYPUFF,:MEOWTH,:ODDISH,:BELLSPROUT,:SENTRET,:SKITTY,:ZIGZAGOON,:PATRAT,:LILLIPUP,:SKIDDO,:WOOLOO,:LECHONK]
    }
    MAID = {
        :TRAINERS => [:MAID],
        :EGGGROUP => [:Field]
    }
    MEDIUM = {
        :TRAINERS => [:MEDIUM],
        :ONLYTYPE => [:PSYCHIC,:GHOST],
        :MAINPOKEMON => [:GASTLY,:MISDREAVUS,:RALTS,:SHUPPET,:DUSKULL,:YAMASK,:LITWICK,:PHANTUMP,:MIMIKYU,:SINISTEA]
    }
    NINJABOY = {
        :TRAINERS => [:NINJABOY],
        :ONLYTYPE => [:POISON],
        :MAINPOKEMON => [:NINCADA,:NINJASK,:ZUBAT,:KOFFING,:GRIMER,:VENIPEDE,:SKORUPI,:SALANDIT,:SHROODLE]
    }
    OFFICELADY = {
        :TRAINERS => [:OFFICELADY]
    }
    OWNER = {
        :TRAINERS => [:OWNER],
        :POWER => [450],
        :SPECIAL => [:VARIED]
    }
    PAINTER = {
        :TRAINERS => [:PAINTER,:PAINTER2],
        :WHITELIST => [:SMEARGLE]
    }
    PARASOLLADY = {
        :TRAINERS => [:PARASOLLADY],
        :ONLYTYPE => [:WATER],
        :MAINPOKEMON => [:LOTAD,:SURSKIT,:CASTFORM,:SHELLOS,:DUCKLETT,:FROAKIE,:WISHIWASHI]
    }
    PICNICKER = {
        :TRAINERS => [:PICNICKER,:PICNICKER2]
    }
    POKEFAN = {
        :TRAINERS => [:POKEFAN_F,:POKEFAN_F2,:POKEFAN_M,:POKEFAN_M2],
        :EGGGROUP => [:Fairy]
    }
    POKEMANIAC = {
        :TRAINERS => [:POKEMANIAC,:POKEMANIAC2],
        :EGGGROUP => [:Monster]
    }
    PRESCHOOLER = {
        :TRAINERS => [:PRESCHOOLER_F,:PRESCHOOLER_M],
        :WEAKER => [420]
    }
    PSYCHIC = {
        :TRAINERS => [:PSYCHIC_F,:PSYCHIC_F2,:PSYCHIC_F3,:PSYCHIC_M,:PSYCHIC_M2],
        :ONLYTYPE => [:PSYCHIC,:GHOST],
        :MAINPOKEMON => [:ABRA,:DROWZEE,:RALTS,:MEDITITE,:SPOINK,:GOTHITA,:SOLOSIS,:ELGYEM,:ESPURR,:INKAY,:ORANGURU,:HATENNA]
    }
    PUNKTRAINER = {
        :TRAINERS => [:PUNKTRAINER_F,:PUNKTRAINER_M],
        :ONLYTYPE => [:FIRE],
        :MAINPOKEMON => [:GROWLITHE,:VULPIX,:PONYTA,:HOUNDOUR,:NUMEL,:LITLEO,:LITTEN,:SALANDIT,:SCORBUNNY]
    }
    RANGER = {
        :TRAINERS => [:RANGER_F,:RANGER_F2,:RANGER_F3,:RANGER_M,:RANGER_M2,:RANGER_M3],
        :ONLYTYPE => [:GRASS],
        :MAINPOKEMON => [:ODDISH,:BELLSPROUT,:TANGELA,:CHIKORITA,:HOPPIP,:TREECKO,:SEEDOT,:SHROOMISH,:TURTWIG,:BUDEW,:PANSAGE,:CHESPIN,:ROWLET,:GROOKEY,:SPRIGATITO]
    }
    REPORTER = {
        :TRAINERS => [:REPORTER],
        :ONLYTYPE => [:ELECTRIC,:FLYING],
        :MAINPOKEMON => [:MAGNEMITE,:VOLTORB,:PIKACHU,:PIDGEY,:SPEAROW,:EMOLGA,:HELIOPTILE,:ROTOM,:TOGEDEMARU]
    }
    RICHBOY = {
        :TRAINERS => [:RICHBOY,:RICHBOY2],
        :WHITELIST => [:MARILL,:ZIGZAGOON,:SHINX,:SUDOWOODO,:PIPLUP,:LILLIPUP,:FURFROU,:ROCKRUFF,:YAMPER,:FIDOUGH]
    }
    RISINGSTAR = {
        :TRAINERS => [:RISINGSTAR_F,:RISINGSTAR_M],
        :WHITELIST => [:RELICANTH,:PIKACHU,:ABRA,:ELECTRIKE,:RIOLU,:PSYDUCK,:SOLROCK,:LUNATONE,:MAGNEMITE,:GOLDEEN,:BIDOOF,:ODDISH,:MUNNA,:FLABEBE,:ROCKRUFF,:STUFFUL,:GROOKEY,:SCORBUNNY,:SOBBLE,:WOOLOO]
    }
    ROCKER = {
        :TRAINERS => [:ROCKER,:ROCKER2],
        :ONLYTYPE => [:ELECTRIC],
        :MAINPOKEMON => [:PIKACHU,:MAGNEMITE,:VOLTORB,:ELECTRIKE,:SHINX,:BLITZLE,:EMOLGA,:DEDENNE,:TOGEDEMARU,:TOXEL]
    }
    ROLLERSKATER = {
        :TRAINERS => [:ROLLERSKATER_F,:ROLLERSKATER_M],
        :ONLYTYPE => [:FLYING,:ELECTRIC],
        :MAINPOKEMON => [:PIDGEY,:SPEAROW,:PIKACHU,:EMOLGA,:FLETCHLING,:HELIOPTILE,:DEDENNE,:ORICORIO,:ROOKIDEE,:PAWMI]
    }
    ROUGHNECK = {
        :TRAINERS => [:ROUGHNECK],
        :ONLYTYPE => [:FIGHTING,:DARK],
        :MAINPOKEMON => [:MACHOP,:MANKEY,:HOUNDOUR,:POOCHYENA,:CROAGUNK,:SANDILE,:SCRAGGY,:PANCHAM,:PASSIMIAN,:IMPIDIMP,:MASCHIFF]
    }
    RUINMANIAC = {
        :TRAINERS => [:RUINMANIAC,:RUINMANIAC2,:RUINMANIAC3],
        :ONLYTYPE => [:GROUND,:ROCK,:STEEL],
        :MAINPOKEMON => [:GEODUDE,:BRONZOR,:SANDSHREW,:SANDSLASH,:ROGGENROLA,:BALTOY,:GOLETT,:CARBINK,:STONJOURNER]
    }
    SAILOR = {
        :TRAINERS => [:SAILOR,:SAILOR2,:SAILOR3],
        :ONLYTYPE => [:WATER],
        :MAINPOKEMON => [:MACHOP,:RATICATE,:TENTACOOL,:HORSEA,:SHELLDER,:CORPHISH,:CLAMPERL,:SHELLOS,:TYMPOLE,:CLAUNCHER,:WIMPOD]
    }
    SCHOOLKID = {
        :TRAINERS => [:SCHOOLBOY,:SCHOOLBOY2,:SCHOOLBOY3,:SCHOOLBOY4,:SCHOOLBOY5,:SCHOOLGIRL,:SCHOOLGIRL2,:SCHOOLGIRL3,:SCHOOLGIRL4],
        :WHITELIST => [:SHROOMISH,:WURMPLE,:RALTS,:MEDITITE,:BANNETE,:WHISMUR,:NUMEL,:ODDISH,:WINGULL,:GASTLY,:ABRA,:WOOPER,:MRMIME,:DRIFLOON,:PACHIRISU,
        :TANGELA,:YANMA,:NATU,:PARAS,:DITTO,:POLIWAG,:MAGNEMITE,:ZIGZAGOON,:JYNX,:ELECTABUZZ,:MAGMAR,:VOLTORB,:EEVEE,:GROWLITHE,:BELLSPROUT,:LEDYBA,:EXEGGCUTE,
        :AIPOM,:SENTRET,:PIDGEY,:SANDSHREW,:ZUBAT,:VULPIX,:ROSELIA,:MUNNA,:SEWADDLE,:VENIPEDE,:COTTONEE,:PETILIL,:FLABEBE,:ESPURR,:BOUNSWEET,:CUTIEFLY,:HATENNA,:FIDOUGH]
    }
    SCIENTIST = {
        :TRAINERS => [:SCIENTIST_F,:SCIENTIST_M,:SCIENTIST_M2,:SCIENTIST_M3],
        :ONLYTYPE => [:PSYCHIC],
        :MAINPOKEMON => [:PORYGON,:MUK,:VOLTORB,:MAGNEMITE,:GRIMER,:KOFFING,:CASTFORM,:BRONZOR,:TRUBBISH,:SOLOSIS,:KLINK,:KLEFKI,:SINISTEA,:VAROOM]
    }
    SISANDBRO = {
        :TRAINERS => [:SISANDBRO],
        :ONLYTYPE => [:WATER]
    }
    SKYTRAINER = {
        :TRAINERS => [:SKYTRAINER_F,:SKYTRAINER_M],
        :ONLYTYPE => [:FLYING],
        :MAINPOKEMON => [:PIDGEY,:SPEAROW,:HOOTHOOT,:TAILLOW,:STARLY,:PIDOVE,:FLETCHLING,:PIKIPEK,:ROOKIDEE,:WATTREL]
    }
    SOCIALITE = {
        :TRAINERS => [:SOCIALITE],
        :WHITELIST => [:BUNEARY,:GLAMEOW,:ROSELIA,:MINCCINO,:FLABEBE,:FURFROU,:BOUNSWEET,:CUTIEFLY,:MILCERY,:FIDOUGH]
    }
    STREETTHUG = {
        :TRAINERS => [:STREETTHUG],
        :ONLYTYPE => [:DARK],
        :MAINPOKEMON => [:RATTATA,:MEOWTH,:HOUNDOUR,:POOCHYENA,:PURRLOIN,:SCRAGGY,:ZORUA,:INKAY,:NICKIT,:IMPIDIMP,:MASCHIFF]
    }
    SUPERNERD = {
        :TRAINERS => [:SUPERNERD,:SUPERNERD2,:SUPERNERD3],
        :ONLYTYPE => [:POISON,:ELECTRIC],
        :MAINPOKEMON => [:GRIMER,:KOFFING,:MAGNEMITE,:VOLTORB,:PORYGON,:TRUBBISH,:FOONGUS,:KLINK,:HELIOPTILE]
    }
    SWIMMER = {
        :TRAINERS => [:SWIMMER_F,:SWIMMER_F2,:SWIMMER_F3,:SWIMMER_F4,:SWIMMER_F5,:SWIMMER_M,:SWIMMER_M2,:SWIMMER_M3],
        :ONLYTYPE => [:WATER],
        :MAINPOKEMON => [:TENTACOOL,:GOLDEEN,:MAGIKARP,:STARYU,:HORSEA,:MARILL,:WINGULL,:CARVANHA,:BARBOACH,:FINNEON,:TYMPOLE,:FRILLISH,:CLAUNCHER,:WISHIWASHI,:ARROKUDA]
    }
    TAMER = {
        :TRAINERS => [:TAMER],
        :LEARNMOVE => [:SLASH,:CRABHAMMER]
    }
    TEACHER = {
        :TRAINERS => [:TEACHER],
        :WHITELIST => [:ZIGZAGOON,:ROSELIA,:CLEFAIRY,:AIPOM,:SUNKERN,:CHATOT,:JIGGLYPUFF,:LILLIPUP,:MINCCINO,:DEERLING,:BUNNELBY,:FLABEBE,:BOUNSWEET,:MILCERY]
    }
    TEAMMATES = {
        :TRAINERS => [:TEAMMATES],
        :SPECIAL => [:VARIED]
    }
    TOURIST = {
        :TRAINERS => [:TOURIST_F,:TOURIST_F2,:TOURIST_M]
    }
    TRIATHLETE_SWIMMING = {
        :TRAINERS => [:TRIATHLETE],
        :ONLYTYPE => [:WATER],
        :MAINPOKEMON => [:MAGIKARP,:GOLDEEN,:TENTACOOL,:WINGULL,:CARVANHA,:FINNEON,:BASCULIN,:WISHIWASHI]
    }
    TRIATHLETE_RUNNING = {
        :TRAINERS => [:TRIATHLETE2],
        :WHITELIST => [:DODUO,:DODRIO,:PONYTA,:RAPIDASH,:ELECTRIKE,:MANECTRIC,:ZEBSTRIKA]
    }
    TRIATHLETE_RIDING = {
        :TRAINERS => [:TRIATHLETE3],
        :ONLYTYPE => [:ELECTRIC],
        :MAINPOKEMON => [:PIKACHU,:MAGNEMITE,:VOLTORB,:ELECTRIKE,:SHINX,:BLITZLE,:EMOLGA,:HELIOPTILE]
    }
    TUBER = {
        :TRAINERS => [:TUBER_F,:TUBER_F2,:TUBER_F3,:TUBER_M,:TUBER_M2,:TUBER_M3],
        :ONLYTYPE => [:WATER,:NORMAL],
        :MAINPOKEMON => [:MARILL,:ZIGZAGOON,:AZURILL,:WINGULL,:SPHEAL,:BUIZEL,:BIDOOF,:OSHAWOTT,:DUCKLETT,:FROAKIE,:POPPLIO,:SOBBLE]
    }
    TWINS = {
        :TRAINERS => [:TWINS,:TWINS2,:TWINS3],
        :WHITELIST => [:PLUSLE,:MINUN,:SEEDOT,:LOTAD,:WURMPLE,:WHISMUR,:CLEFAIRY,:JIGGLYPUFF,:EEVEE,:SUDOWOODO,:MRMIME,:PACHIRISU,:SPINARAK,:LEDYBA,:BELLSPROUT,:ODDISH,:WOOPER,
        :TEDDIURSA,:PHANPY,:MARILL,:MAREEP,:SOLOSIS,:GOTHITA,:FLABEBE,:ESPURR,:BOUNSWEET,:CUTIEFLY,:HATENNA,:TANDEMAUS]
    }
    VETERAN = {
        :TRAINERS => [:VETERAN_F,:VETERAN_M]
    }
    WAITER = {
        :TRAINERS => [:WAITER,:WAITRESS],
        :ONLYTYPE => [:NORMAL],
        :MAINPOKEMON => [:MEOWTH,:JIGGLYPUFF,:TEDDIURSA,:SKITTY,:GLAMEOW,:MINCCINO,:LILLIPUP,:FURFROU,:SKWOVET,:TANDEMAUS]
    }
    WORKER = {
        :TRAINERS => [:WORKER,:WORKER2],
        :ONLYTYPE => [:ROCK,:FIGHTING,:STEEL,:GROUND],
        :MAINPOKEMON => [:MACHOP,:GEODUDE,:ONIX,:TIMBURR,:ROGGENROLA,:DRILBUR,:ROLYCOLY,:CUFANT,:NACLI]
    }
    YOUNGCOUPLE = {
        :TRAINERS => [:YOUNGCOUPLE,:YOUNGCOUPLE2]
    }
    YOUNGSTER = {
        :TRAINERS => [:YOUNGSTER,:YOUNGSTER2,:YOUNGSTER3],
        :ONLYTYPE => [:BUG,:NORMAL],
        :MAINPOKEMON => [:RATTATA,:PIDGEY,:CATERPIE,:WEEDLE,:SENTRET,:ZIGZAGOON,:WURMPLE,:PATRAT,:LILLIPUP,:SCATTERBUG,:YUNGOOS,:SKWOVET,:LECHONK]
    }
end